<?php 
global $hotelConstants;
$hotelConstants = [
                   'Anand_Resort'=>['name'=>'Anand Resort',
                                   'city'=> 'New Delhi',
                                   'address'=>'Janakpuri'],
                   'Bajaj_Indian'=>['name'=>'Bajaj Indian West Resort',
                                   'city'=> 'Panipat',
                                   'address'=>'Model Town'],
                    'Casa_Cottage'=>['name'=>'Casa Cottage',
                                   'city'=> 'Mumbai',
                                   'address'=>'Marine Drive'],
                    'Deep_Jungle'=>['name'=>'Deep Jungle Hotel',
                                   'city'=> 'Munnar',
                                   'address'=>'M-10'],
                    'Express_Inn'=>['name'=>'Express Inn',
                                   'city'=> 'New Delhi',
                                   'address'=>'Vivek Vihar'],
                    'Fortune_Inn'=>['name'=>'Fortune Inn Valley View',
                                   'city'=> 'Mussorie',
                                   'address'=>'H-12,Manas Road'],                                                                
                    'Grand_View'=>['name'=>'Hotel Grand View',
                                   'city'=> 'New Delhi',
                                   'address'=>'Preet Vihar'],
                    'Heritage'=>['name'=>'Hotel Heritage',
                                   'city'=> 'New Delhi',
                                   'address'=>'Udyog Vihar'],
                    'Ibis_Hotel'=>['name'=>'Hotel Ibis',
                                   'city'=> 'Jaipur',
                                   'address'=>'Near Hawa Mehel'],
                    'Jennifer_In'=>['name'=>'Jennifer In',
                                   'city'=> 'New Delhi',
                                   'address'=>'Preet Vihar'],
                    'Karni_Bhawan'=>['name'=>'Karni Bhawan Palace',
                                   'city'=> 'Gurgaon',
                                   'address'=>'Udyog Vihar'],   
                    'Le_Meridian'=>['name'=>'Le Meridian',
                                   'city'=> 'Gurgaon',
                                   'address'=>'Udyog Vihar'], 
                    'Marine_View'=>['name'=>'Hotel Marine View',
                                   'city'=> 'New Delhi',
                                   'address'=>'Preet Vihar'],              
                    'Nagarjuna_Suites'=>['name'=>'Nagarjuna Suites',
                                   'city'=> 'Gurgaon',
                                   'address'=>'Udyog Vihar'], 
                    'Oakwood_Residency'=>['name'=>'Oakwood Residency',
                                   'city'=> 'Gurgaon',
                                   'address'=>'Udyog Vihar'],                                                                                                           
                                                                    

                 ];

?>